/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-5月-2018 16:21:01 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0

/* Create Tables */

CREATE TABLE `comment_thumbup`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT ,
	`comment_id` BIGINT NOT NULL,
	`thumb_userid` VARCHAR(200) NOT NULL COMMENT '点赞人id',
	CONSTRAINT `PK_comment_thumbup` PRIMARY KEY (`id`)
) COMMENT='评论点赞表'
;

SET FOREIGN_KEY_CHECKS=1
