/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-5月-2018 15:37:10 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0

/* Create Tables */

CREATE TABLE `depart_user`
(
	`id` BIGINT NOT NULL COMMENT '主键',
	`depart_id` VARCHAR(50) NOT NULL COMMENT '部门id',
	`user_id` VARCHAR(50) NOT NULL COMMENT '用户id',
	CONSTRAINT `PK_depart_user` PRIMARY KEY (`id`)
) COMMENT='部门 用户关系表'
;

SET FOREIGN_KEY_CHECKS=1
