/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-5月-2018 12:08:08 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0

/* Create Tables */

CREATE TABLE `wx_user`
(
	`user_id` VARCHAR(200) NOT NULL COMMENT 'userId， 可以有多个相同的id， 部门可能是不同的',
	`user_name` VARCHAR(200) COMMENT '用户名',
	`user_depart_id` VARCHAR(200) NOT NULL COMMENT '用户部门',
	`avatar` VARCHAR(50) COMMENT '用户头像',
	`user_depart_name` VARCHAR(200) COMMENT '部门名',
	CONSTRAINT `PK_wx_user` PRIMARY KEY (`user_id`,`user_depart_id`)
) COMMENT='所有微信用户'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `wx_user` 
 ADD CONSTRAINT `UQ_wx_user_id` UNIQUE ()
;

ALTER TABLE `wx_user` 
 ADD CONSTRAINT `UQ_wx_user_user_name` UNIQUE (`user_name`)
;

SET FOREIGN_KEY_CHECKS=1
