package org.saxing.test;

import org.saxing.drools.entity.Student

rule "e_lhs_1"
    when
        // 多个对象，只触发一次
        exists Student()
    then
        System.out.println("e_lhs_1 多个对象，只触发一次");
end


rule "e_lhs_2"
    when
        // 多个对象，触发多次次
        Student()
    then
        System.out.println("e_lhs_2 多个对象，触发多次次");
end


rule "e_lhs_6"
    when
        // 多个对象，触发多次次
        $s6:Student(age > 10)
    then
        System.out.println("e_lhs_6: " + $s6);
end

rule "e_lhs_7" extends "e_lhs_6"
    when
        // 多个对象，触发多次次
        $s7:Student(age < 100)
    then
        System.out.println("e_lhs_7: " + $s7);

end
