package org.saxing.test

import org.saxing.drools.entity.Student

// rule_noloop1
rule "rule_noloop1"
    no-loop true
    enabled false
    when
        $s:Student(age == 50)
    then
        $s.setAge(100);
        update($s)
        System.out.println("rule_noloop1 trigger");
end

// rule_noloop2
rule "rule_noloop2"
    no-loop true
    enabled false
    when
        $s:Student(age == 100)
    then
        $s.setAge(50);
        update($s)
        System.out.println("rule_noloop2 trigger");
end

// rule_noloop3
rule "rule_noloop3"
    no-loop true
    when
        $s:Student(age == 50)
    then
        update($s)
        System.out.println("rule_noloop3 trigger");
end




